/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdibujo;

import javax.swing.JOptionPane;

/**
 *
 * @author Ani
 */
public class FormularioARG extends javax.swing.JDialog {

    /**
     * Creates new form formularioApp
     */
    public FormularioARG(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Centramos la ventana
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanelBackground = new javax.swing.JPanel();
        jPanelContenedorImg = new javax.swing.JPanel();
        jLabelVistaPrevia = new javax.swing.JLabel();
        jPanelInfo = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelFormato = new javax.swing.JLabel();
        jComboBoxFormato = new javax.swing.JComboBox();
        jPanelConf = new javax.swing.JPanel();
        jLabelImpresora = new javax.swing.JLabel();
        jComboBoxImpresora = new javax.swing.JComboBox();
        jLabelCopias = new javax.swing.JLabel();
        jLabelCompo = new javax.swing.JLabel();
        jRadioButtonHorizontal = new javax.swing.JRadioButton();
        jRadioButtonVertical = new javax.swing.JRadioButton();
        jSpinnerCopias = new javax.swing.JSpinner();
        jPanelFuncTama = new javax.swing.JPanel();
        jButtonSangrado = new javax.swing.JButton();
        jButtonBorde = new javax.swing.JButton();
        jButtonFondo = new javax.swing.JButton();
        jLabelTamanio = new javax.swing.JLabel();
        jComboBoxTamanio = new javax.swing.JComboBox();
        jButtonImprimir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jCheckBoxColor = new javax.swing.JCheckBox();
        jCheckBoxBYN = new javax.swing.JCheckBox();
        jCheckBoxEscalaGrises = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajustes de impresión");

        jPanelBackground.setBackground(new java.awt.Color(102, 102, 102));
        jPanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelContenedorImg.setBackground(new java.awt.Color(51, 51, 51));

        jLabelVistaPrevia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVistaPrevia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appdibujo/img/vistaPrevia_impresion.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelContenedorImgLayout = new javax.swing.GroupLayout(jPanelContenedorImg);
        jPanelContenedorImg.setLayout(jPanelContenedorImgLayout);
        jPanelContenedorImgLayout.setHorizontalGroup(
            jPanelContenedorImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorImgLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelVistaPrevia, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContenedorImgLayout.setVerticalGroup(
            jPanelContenedorImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorImgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVistaPrevia, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        jPanelBackground.add(jPanelContenedorImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 290, 400));

        jPanelInfo.setBackground(new java.awt.Color(102, 102, 102));
        jPanelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información del archivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelInfo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelInfo.setToolTipText("Panel para seleccionar opciones del archivo");
        jPanelInfo.setName("jPanelArchivo"); // NOI18N
        jPanelInfo.setOpaque(false);

        jLabelNombre.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(204, 204, 204));
        jLabelNombre.setText("Nombre: ");

        jLabelFormato.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelFormato.setForeground(new java.awt.Color(204, 204, 204));
        jLabelFormato.setText("Formato: ");

        jComboBoxFormato.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxFormato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PDF", "JPG", "TIFF", "PNG" }));

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addComponent(jLabelFormato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxFormato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFormato)
                    .addComponent(jComboBoxFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBackground.add(jPanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 300, 140));
        jPanelInfo.getAccessibleContext().setAccessibleName("Archivo");

        jPanelConf.setBackground(new java.awt.Color(102, 102, 102));
        jPanelConf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuración de impresora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelConf.setOpaque(false);

        jLabelImpresora.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelImpresora.setForeground(new java.awt.Color(204, 204, 204));
        jLabelImpresora.setText("Impresora: ");

        jComboBoxImpresora.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxImpresora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EPSON SX525WD", "Canon PIXMA TS3451", "Microsoft print to PDF", " " }));

        jLabelCopias.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelCopias.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCopias.setText("Copias: ");

        jLabelCompo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelCompo.setForeground(new java.awt.Color(204, 204, 204));
        jLabelCompo.setText("Composición: ");

        jRadioButtonHorizontal.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(jRadioButtonHorizontal);
        jRadioButtonHorizontal.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jRadioButtonHorizontal.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonHorizontal.setText("Horizontal");

        jRadioButtonVertical.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(jRadioButtonVertical);
        jRadioButtonVertical.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jRadioButtonVertical.setForeground(new java.awt.Color(204, 204, 204));
        jRadioButtonVertical.setText("Vertical");

        jSpinnerCopias.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanelConfLayout = new javax.swing.GroupLayout(jPanelConf);
        jPanelConf.setLayout(jPanelConfLayout);
        jPanelConfLayout.setHorizontalGroup(
            jPanelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelConfLayout.createSequentialGroup()
                        .addComponent(jLabelCompo)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonHorizontal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonVertical))
                    .addGroup(jPanelConfLayout.createSequentialGroup()
                        .addGroup(jPanelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelImpresora)
                            .addComponent(jLabelCopias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
        );
        jPanelConfLayout.setVerticalGroup(
            jPanelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImpresora)
                    .addComponent(jComboBoxImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCopias)
                    .addComponent(jSpinnerCopias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelConfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCompo)
                    .addComponent(jRadioButtonHorizontal)
                    .addComponent(jRadioButtonVertical))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanelBackground.add(jPanelConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 300, 140));

        jPanelFuncTama.setBackground(new java.awt.Color(102, 102, 102));
        jPanelFuncTama.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funciones y tamaño", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelFuncTama.setOpaque(false);

        jButtonSangrado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButtonSangrado.setText("Sangrado...");

        jButtonBorde.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButtonBorde.setText("Borde...");

        jButtonFondo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButtonFondo.setText("Fondo...");

        jLabelTamanio.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelTamanio.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTamanio.setText("Tamaño: ");

        jComboBoxTamanio.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxTamanio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A3", "A4", "A5", "A6" }));

        javax.swing.GroupLayout jPanelFuncTamaLayout = new javax.swing.GroupLayout(jPanelFuncTama);
        jPanelFuncTama.setLayout(jPanelFuncTamaLayout);
        jPanelFuncTamaLayout.setHorizontalGroup(
            jPanelFuncTamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncTamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFuncTamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFuncTamaLayout.createSequentialGroup()
                        .addComponent(jButtonSangrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorde)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFondo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelFuncTamaLayout.createSequentialGroup()
                        .addComponent(jLabelTamanio)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxTamanio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelFuncTamaLayout.setVerticalGroup(
            jPanelFuncTamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFuncTamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFuncTamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTamanio)
                    .addComponent(jComboBoxTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelFuncTamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSangrado)
                    .addComponent(jButtonBorde)
                    .addComponent(jButtonFondo))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelBackground.add(jPanelFuncTama, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 300, 120));

        jButtonImprimir.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        jPanelBackground.add(jButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        jButtonCancelar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelBackground.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, -1, -1));

        jCheckBoxColor.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup2.add(jCheckBoxColor);
        jCheckBoxColor.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jCheckBoxColor.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBoxColor.setText("Color");
        jPanelBackground.add(jCheckBoxColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jCheckBoxBYN.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup2.add(jCheckBoxBYN);
        jCheckBoxBYN.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jCheckBoxBYN.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBoxBYN.setText("Blanco y negro");
        jPanelBackground.add(jCheckBoxBYN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        jCheckBoxEscalaGrises.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup2.add(jCheckBoxEscalaGrises);
        jCheckBoxEscalaGrises.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jCheckBoxEscalaGrises.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBoxEscalaGrises.setText("Escala de grises");
        jPanelBackground.add(jCheckBoxEscalaGrises, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        //Se cierra la ventana
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        //Si se selecciona la impresora Canon se lanza el mensaje de error
        String seleccion = (String) jComboBoxImpresora.getSelectedItem();
        String nombreArchivo = jTextFieldNombre.getText();

        //Simulación de riesgo de sobreescritura
        if (nombreArchivo.equals("obra1")) {
            MensajeDeAviso02 mensajeAvisoSobreescritura = new MensajeDeAviso02(null, true);
            mensajeAvisoSobreescritura.setVisible(true);
        }

        //Simulación de seleccion de impresora no disponible
        if (seleccion.equals("Canon PIXMA TS3451")) {
            MensajeDeAviso01 mensajeErrorImpresora = new MensajeDeAviso01(null, true);
            mensajeErrorImpresora.setVisible(true);
        } else if (seleccion.equals("EPSON SX525WD")) {
            JOptionPane.showMessageDialog(this, "El archivo se ha mandado a la lista de tareas de la impresora seleccionada.");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Archivo guardado como pdf");
            this.dispose();
        }


    }//GEN-LAST:event_jButtonImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioARG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioARG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioARG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioARG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioARG dialog = new FormularioARG(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonBorde;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonFondo;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonSangrado;
    private javax.swing.JCheckBox jCheckBoxBYN;
    private javax.swing.JCheckBox jCheckBoxColor;
    private javax.swing.JCheckBox jCheckBoxEscalaGrises;
    private javax.swing.JComboBox jComboBoxFormato;
    private javax.swing.JComboBox jComboBoxImpresora;
    private javax.swing.JComboBox jComboBoxTamanio;
    private javax.swing.JLabel jLabelCompo;
    private javax.swing.JLabel jLabelCopias;
    private javax.swing.JLabel jLabelFormato;
    private javax.swing.JLabel jLabelImpresora;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTamanio;
    private javax.swing.JLabel jLabelVistaPrevia;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelConf;
    private javax.swing.JPanel jPanelContenedorImg;
    private javax.swing.JPanel jPanelFuncTama;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JRadioButton jRadioButtonHorizontal;
    private javax.swing.JRadioButton jRadioButtonVertical;
    private javax.swing.JSpinner jSpinnerCopias;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
