/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdibujo;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Ani
 */
public class MensajeDeAviso01 extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form MensajeDeAviso01
     */
    public MensajeDeAviso01(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Centramos la ventana
        this.setLocationRelativeTo(null);

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabelIconAviso = new javax.swing.JLabel();
        jLabelTextoInformativo = new javax.swing.JLabel();
        jPanelContenedorOpciones = new javax.swing.JPanel();
        jRadioButtonSeleccionarImpresora = new javax.swing.JRadioButton();
        jRadioButtonGuardarArchivo = new javax.swing.JRadioButton();
        jComboBoxImpresora = new javax.swing.JComboBox();
        okButtonAceptar = new javax.swing.JButton();
        cancelButtonCancelar = new javax.swing.JButton();

        setTitle("La impresora no responde");
        setBackground(new java.awt.Color(51, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabelIconAviso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appdibujo/resources/imgIcon/warning-sign.png"))); // NOI18N

        jLabelTextoInformativo.setBackground(new java.awt.Color(51, 51, 51));
        jLabelTextoInformativo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelTextoInformativo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoInformativo.setText("La impresora seleccionada no responde o no se encuentra disponible. ");

        jPanelContenedorOpciones.setBackground(new java.awt.Color(51, 51, 51));
        jPanelContenedorOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "¿Qué desea hacer?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanelContenedorOpciones.setForeground(new java.awt.Color(255, 255, 255));

        jRadioButtonSeleccionarImpresora.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButtonSeleccionarImpresora);
        jRadioButtonSeleccionarImpresora.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jRadioButtonSeleccionarImpresora.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSeleccionarImpresora.setText("Seleccionar otra impresora");

        jRadioButtonGuardarArchivo.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(jRadioButtonGuardarArchivo);
        jRadioButtonGuardarArchivo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jRadioButtonGuardarArchivo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonGuardarArchivo.setText("Guardar archivo");

        jComboBoxImpresora.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxImpresora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EPSON SX525WD", "Canon PIXMA TS3451", "Microsoft print to PDF" }));

        javax.swing.GroupLayout jPanelContenedorOpcionesLayout = new javax.swing.GroupLayout(jPanelContenedorOpciones);
        jPanelContenedorOpciones.setLayout(jPanelContenedorOpcionesLayout);
        jPanelContenedorOpcionesLayout.setHorizontalGroup(
            jPanelContenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorOpcionesLayout.createSequentialGroup()
                        .addComponent(jRadioButtonGuardarArchivo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelContenedorOpcionesLayout.createSequentialGroup()
                        .addComponent(jRadioButtonSeleccionarImpresora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jComboBoxImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelContenedorOpcionesLayout.setVerticalGroup(
            jPanelContenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorOpcionesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanelContenedorOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSeleccionarImpresora)
                    .addComponent(jComboBoxImpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonGuardarArchivo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButtonAceptar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        okButtonAceptar.setText("Aceptar");
        okButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonAceptarActionPerformed(evt);
            }
        });

        cancelButtonCancelar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        cancelButtonCancelar.setText("Cancelar");
        cancelButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(okButtonAceptar)
                        .addGap(33, 33, 33)
                        .addComponent(cancelButtonCancelar))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanelContenedorOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelIconAviso)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelTextoInformativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTextoInformativo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIconAviso))
                .addGap(18, 18, 18)
                .addComponent(jPanelContenedorOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButtonAceptar)
                    .addComponent(cancelButtonCancelar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(okButtonAceptar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonAceptarActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonAceptarActionPerformed

    private void cancelButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonCancelarActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonCancelarActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MensajeDeAviso01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MensajeDeAviso01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MensajeDeAviso01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MensajeDeAviso01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MensajeDeAviso01 dialog = new MensajeDeAviso01(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButtonCancelar;
    private javax.swing.JComboBox jComboBoxImpresora;
    private javax.swing.JLabel jLabelIconAviso;
    private javax.swing.JLabel jLabelTextoInformativo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelContenedorOpciones;
    private javax.swing.JRadioButton jRadioButtonGuardarArchivo;
    private javax.swing.JRadioButton jRadioButtonSeleccionarImpresora;
    private javax.swing.JButton okButtonAceptar;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
