/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appdibujo;

/**
 *
 * @author Ani
 */
public class PrincipalARG extends javax.swing.JFrame {

    /**
     * Creates new form lienzoApp
     */
    public PrincipalARG() {
        initComponents();
        //Centramos la ventana
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrouoBarraHerramientas = new javax.swing.ButtonGroup();
        buttonGroupVentana = new javax.swing.ButtonGroup();
        jPanelBackground = new javax.swing.JPanel();
        jPanelInfo = new javax.swing.JPanel();
        jLabelNombreArtista = new javax.swing.JLabel();
        jLabelLineaDiv = new javax.swing.JLabel();
        jLabelNombreObra = new javax.swing.JLabel();
        jLabelTecnica = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        barraHerramientas = new javax.swing.JToolBar();
        jToggleButtonPincel = new javax.swing.JToggleButton();
        jToggleButtonGoma = new javax.swing.JToggleButton();
        jToggleButtonColor = new javax.swing.JToggleButton();
        jToggleButtonPaleta = new javax.swing.JToggleButton();
        jButtonDeshacer = new javax.swing.JButton();
        jButtonRehacer = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jPanelContenedorImgRef = new javax.swing.JPanel();
        ImgRef = new javax.swing.JLabel();
        jPanelContenedorImgBYN = new javax.swing.JPanel();
        ImgBYN = new javax.swing.JLabel();
        jMenuBarraMenu = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jSeparatorAbrirCerrar = new javax.swing.JPopupMenu.Separator();
        jMenuItemCerrar = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jMenuItemGuardarComo = new javax.swing.JMenuItem();
        jSeparatorGuardarImprimir = new javax.swing.JPopupMenu.Separator();
        jMenuItemImprimir = new javax.swing.JMenuItem();
        jSeparatorImprimirSalir = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuTools = new javax.swing.JMenu();
        jMenuItemPincel = new javax.swing.JMenuItem();
        jMenuItemGoma = new javax.swing.JMenuItem();
        jSeparatorGomaColor = new javax.swing.JPopupMenu.Separator();
        jMenuItemColor = new javax.swing.JMenuItem();
        jMenuItemPaleta = new javax.swing.JMenuItem();
        jSeparatorPaletaDeshacer = new javax.swing.JPopupMenu.Separator();
        jMenuItemDesh = new javax.swing.JMenuItem();
        jMenuItemRehac = new javax.swing.JMenuItem();
        jMenuGaleria = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparatorVerSelec = new javax.swing.JPopupMenu.Separator();
        jMenuItemSelecArt = new javax.swing.JMenuItem();
        jMenuVentana = new javax.swing.JMenu();
        jCheckBoxMenuItemZurdos = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDiestros = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);

        jPanelBackground.setBackground(new java.awt.Color(102, 102, 102));
        jPanelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelInfo.setBackground(new java.awt.Color(255, 204, 0));

        jLabelNombreArtista.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabelNombreArtista.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNombreArtista.setText("Leonardo Da Vinci");

        jLabelLineaDiv.setText("___________________");

        jLabelNombreObra.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelNombreObra.setForeground(new java.awt.Color(102, 102, 102));
        jLabelNombreObra.setText("\"La dama del armiño\"");

        jLabelTecnica.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelTecnica.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTecnica.setText("Óleo y temple sobre tabla de nogal");

        jLabelFecha.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(102, 102, 102));
        jLabelFecha.setText("1489-1491");

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFecha)
                    .addComponent(jLabelNombreArtista)
                    .addComponent(jLabelLineaDiv)
                    .addComponent(jLabelNombreObra, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTecnica))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNombreArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLineaDiv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombreObra)
                .addGap(9, 9, 9)
                .addComponent(jLabelTecnica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelFecha)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanelBackground.add(jPanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 450, 170));

        barraHerramientas.setBackground(new java.awt.Color(102, 102, 102));
        barraHerramientas.setRollover(true);

        jToggleButtonPincel.setBackground(new java.awt.Color(102, 102, 102));
        buttonGrouoBarraHerramientas.add(jToggleButtonPincel);
        jToggleButtonPincel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appdibujo/resources/imgIcon/paint-brush (1).png"))); // NOI18N
        jToggleButtonPincel.setToolTipText("Selecciona la herramienta de pincel");
        barraHerramientas.add(jToggleButtonPincel);

        jToggleButtonGoma.setBackground(new java.awt.Color(102, 102, 102));
        buttonGrouoBarraHerramientas.add(jToggleButtonGoma);
        jToggleButtonGoma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appdibujo/resources/imgIcon/eraser.png"))); // NOI18N
        jToggleButtonGoma.setToolTipText("Selecciona la herramienta para borrar");
        barraHerramientas.add(jToggleButtonGoma);

        jToggleButtonColor.setBackground(new java.awt.Color(102, 102, 102));
        buttonGrouoBarraHerramientas.add(jToggleButtonColor);
        jToggleButtonColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appdibujo/resources/imgIcon/stop.png"))); // NOI18N
        jToggleButtonColor.setToolTipText("Para ver el color en uso actual");
        barraHerramientas.add(jToggleButtonColor);

        jToggleButtonPaleta.setBackground(new java.awt.Color(102, 102, 102));
        buttonGrouoBarraHerramientas.add(jToggleButtonPaleta);
        jToggleButtonPaleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appdibujo/resources/imgIcon/color-palette (2).png"))); // NOI18N
        jToggleButtonPaleta.setToolTipText("Para seleccionar un nuevo color de la paleta");
        barraHerramientas.add(jToggleButtonPaleta);

        jButtonDeshacer.setBackground(new java.awt.Color(102, 102, 102));
        jButtonDeshacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appdibujo/resources/imgIcon/share_izq.png"))); // NOI18N
        jButtonDeshacer.setToolTipText("Deshace la ultima acción realizada");
        barraHerramientas.add(jButtonDeshacer);

        jButtonRehacer.setBackground(new java.awt.Color(102, 102, 102));
        jButtonRehacer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRehacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appdibujo/resources/imgIcon/share_derecha.png"))); // NOI18N
        jButtonRehacer.setToolTipText("Rehace la última acción realizada");
        barraHerramientas.add(jButtonRehacer);

        jButtonGuardar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appdibujo/resources/imgIcon/save.png"))); // NOI18N
        jButtonGuardar.setToolTipText("Guarda el archivo en el estado actual");
        barraHerramientas.add(jButtonGuardar);

        jPanelBackground.add(barraHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 900, 30));

        jPanelContenedorImgRef.setBackground(new java.awt.Color(0, 0, 0));

        ImgRef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgRef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appdibujo/img/Lady_with_an_Ermine_-_Leonardo_da_Vinci_(peq).jpg"))); // NOI18N
        ImgRef.setLabelFor(ImgRef);

        javax.swing.GroupLayout jPanelContenedorImgRefLayout = new javax.swing.GroupLayout(jPanelContenedorImgRef);
        jPanelContenedorImgRef.setLayout(jPanelContenedorImgRefLayout);
        jPanelContenedorImgRefLayout.setHorizontalGroup(
            jPanelContenedorImgRefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorImgRefLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(ImgRef, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelContenedorImgRefLayout.setVerticalGroup(
            jPanelContenedorImgRefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorImgRefLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ImgRef))
        );

        jPanelBackground.add(jPanelContenedorImgRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 450, 510));

        jPanelContenedorImgBYN.setBackground(new java.awt.Color(255, 255, 255));

        ImgBYN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appdibujo/img/colorear-para-adultos-obra-de-arte-70.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelContenedorImgBYNLayout = new javax.swing.GroupLayout(jPanelContenedorImgBYN);
        jPanelContenedorImgBYN.setLayout(jPanelContenedorImgBYNLayout);
        jPanelContenedorImgBYNLayout.setHorizontalGroup(
            jPanelContenedorImgBYNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContenedorImgBYNLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(ImgBYN, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanelContenedorImgBYNLayout.setVerticalGroup(
            jPanelContenedorImgBYNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorImgBYNLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(ImgBYN, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanelBackground.add(jPanelContenedorImgBYN, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 450, 680));

        jMenuBarraMenu.setBackground(new java.awt.Color(230, 230, 230));
        jMenuBarraMenu.setForeground(new java.awt.Color(255, 255, 255));

        jMenuArchivo.setBackground(new java.awt.Color(230, 230, 230));
        jMenuArchivo.setText("Archivo");

        jMenuItemAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAbrir.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemAbrir.setText("Abrir");
        jMenuArchivo.add(jMenuItemAbrir);

        jSeparatorAbrirCerrar.setBackground(new java.awt.Color(204, 204, 204));
        jSeparatorAbrirCerrar.setForeground(new java.awt.Color(0, 0, 0));
        jMenuArchivo.add(jSeparatorAbrirCerrar);

        jMenuItemCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemCerrar.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemCerrar.setText("Cerrar");
        jMenuArchivo.add(jMenuItemCerrar);

        jMenuItemGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemGuardar.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemGuardar.setText("Guardar");
        jMenuArchivo.add(jMenuItemGuardar);

        jMenuItemGuardarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItemGuardarComo.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemGuardarComo.setText("Guardar como...");
        jMenuArchivo.add(jMenuItemGuardarComo);

        jSeparatorGuardarImprimir.setBackground(new java.awt.Color(204, 204, 204));
        jSeparatorGuardarImprimir.setForeground(new java.awt.Color(0, 0, 0));
        jMenuArchivo.add(jSeparatorGuardarImprimir);

        jMenuItemImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemImprimir.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemImprimir.setText("Imprimir...");
        jMenuItemImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImprimirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemImprimir);

        jSeparatorImprimirSalir.setBackground(new java.awt.Color(204, 204, 204));
        jSeparatorImprimirSalir.setForeground(new java.awt.Color(0, 0, 0));
        jMenuArchivo.add(jSeparatorImprimirSalir);

        jMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSalir.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBarraMenu.add(jMenuArchivo);

        jMenuTools.setBackground(new java.awt.Color(230, 230, 230));
        jMenuTools.setText("Herramientas");

        jMenuItemPincel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemPincel.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemPincel.setText("Pincel");
        jMenuTools.add(jMenuItemPincel);

        jMenuItemGoma.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItemGoma.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemGoma.setText("Goma");
        jMenuTools.add(jMenuItemGoma);

        jSeparatorGomaColor.setBackground(new java.awt.Color(204, 204, 204));
        jSeparatorGomaColor.setForeground(new java.awt.Color(0, 0, 0));
        jMenuTools.add(jSeparatorGomaColor);

        jMenuItemColor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemColor.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemColor.setText("Color");
        jMenuTools.add(jMenuItemColor);

        jMenuItemPaleta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemPaleta.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemPaleta.setText("Paleta");
        jMenuTools.add(jMenuItemPaleta);

        jSeparatorPaletaDeshacer.setBackground(new java.awt.Color(204, 204, 204));
        jSeparatorPaletaDeshacer.setForeground(new java.awt.Color(0, 0, 0));
        jMenuTools.add(jSeparatorPaletaDeshacer);

        jMenuItemDesh.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemDesh.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemDesh.setText("Deshacer");
        jMenuTools.add(jMenuItemDesh);

        jMenuItemRehac.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemRehac.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemRehac.setText("Rehacer");
        jMenuTools.add(jMenuItemRehac);

        jMenuBarraMenu.add(jMenuTools);

        jMenuGaleria.setBackground(new java.awt.Color(230, 230, 230));
        jMenuGaleria.setText("Galería");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItem1.setText("Ver");
        jMenuGaleria.add(jMenuItem1);

        jSeparatorVerSelec.setBackground(new java.awt.Color(204, 204, 204));
        jSeparatorVerSelec.setForeground(new java.awt.Color(0, 0, 0));
        jMenuGaleria.add(jSeparatorVerSelec);

        jMenuItemSelecArt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemSelecArt.setBackground(new java.awt.Color(204, 204, 204));
        jMenuItemSelecArt.setText("Seleccionar obra...");
        jMenuGaleria.add(jMenuItemSelecArt);

        jMenuBarraMenu.add(jMenuGaleria);

        jMenuVentana.setBackground(new java.awt.Color(230, 230, 230));
        jMenuVentana.setText("Ventana");

        jCheckBoxMenuItemZurdos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItemZurdos.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroupVentana.add(jCheckBoxMenuItemZurdos);
        jCheckBoxMenuItemZurdos.setText("Zurdos");
        jMenuVentana.add(jCheckBoxMenuItemZurdos);

        jCheckBoxMenuItemDiestros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jCheckBoxMenuItemDiestros.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroupVentana.add(jCheckBoxMenuItemDiestros);
        jCheckBoxMenuItemDiestros.setSelected(true);
        jCheckBoxMenuItemDiestros.setText("Diestros");
        jMenuVentana.add(jCheckBoxMenuItemDiestros);

        jMenuBarraMenu.add(jMenuVentana);

        setJMenuBar(jMenuBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImprimirActionPerformed
        // para abrir el formulario al clicar sobre el elemento de menú Imprimir
        FormularioARG formularioImpresion = new FormularioARG(this, true);
        formularioImpresion.setVisible(true);
    }//GEN-LAST:event_jMenuItemImprimirActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalARG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalARG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalARG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalARG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalARG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgBYN;
    private javax.swing.JLabel ImgRef;
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.ButtonGroup buttonGrouoBarraHerramientas;
    private javax.swing.ButtonGroup buttonGroupVentana;
    private javax.swing.JButton jButtonDeshacer;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonRehacer;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDiestros;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemZurdos;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelLineaDiv;
    private javax.swing.JLabel jLabelNombreArtista;
    private javax.swing.JLabel jLabelNombreObra;
    private javax.swing.JLabel jLabelTecnica;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBarraMenu;
    private javax.swing.JMenu jMenuGaleria;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemCerrar;
    private javax.swing.JMenuItem jMenuItemColor;
    private javax.swing.JMenuItem jMenuItemDesh;
    private javax.swing.JMenuItem jMenuItemGoma;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemGuardarComo;
    private javax.swing.JMenuItem jMenuItemImprimir;
    private javax.swing.JMenuItem jMenuItemPaleta;
    private javax.swing.JMenuItem jMenuItemPincel;
    private javax.swing.JMenuItem jMenuItemRehac;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemSelecArt;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JMenu jMenuVentana;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelContenedorImgBYN;
    private javax.swing.JPanel jPanelContenedorImgRef;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPopupMenu.Separator jSeparatorAbrirCerrar;
    private javax.swing.JPopupMenu.Separator jSeparatorGomaColor;
    private javax.swing.JPopupMenu.Separator jSeparatorGuardarImprimir;
    private javax.swing.JPopupMenu.Separator jSeparatorImprimirSalir;
    private javax.swing.JPopupMenu.Separator jSeparatorPaletaDeshacer;
    private javax.swing.JPopupMenu.Separator jSeparatorVerSelec;
    private javax.swing.JToggleButton jToggleButtonColor;
    private javax.swing.JToggleButton jToggleButtonGoma;
    private javax.swing.JToggleButton jToggleButtonPaleta;
    private javax.swing.JToggleButton jToggleButtonPincel;
    // End of variables declaration//GEN-END:variables
}
